# Generated by Django 3.2.16 on 2023-07-16 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_auto_20230716_1551"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="name",
        ),
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(default=1, verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="slug",
            field=models.SlugField(default=1, verbose_name="Слаг"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="title",
            field=models.CharField(
                default=1, max_length=200, verbose_name="Название группы"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="follow",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписан на",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
